---
- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart gpsd
  ansible.builtin.service:
    name: gpsd
    state: restarted

- name: Apply netplan
  ansible.builtin.command:
    cmd: netplan apply
  changed_when: true

- name: Restart ptp4l
  ansible.builtin.systemd_service:
    name: ptp4l
    state: restarted
    daemon-reload: true
    
- name: Restart ts2phc
  ansible.builtin.systemd_service:
    name: ts2phc
    state: restarted
    daemon-reload: true

- name: Restart phc2sys
  ansible.builtin.systemd_service:
    name: phc2sys
    state: restarted
    daemon-reload: true